apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dr6g4k24u-go
  janus-idp.io/tekton: dr6g4k24u-go
  backstage.io/kubernetes-id: dr6g4k24u-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dr6g4k24u-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
