apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dr6g4k24u-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dr6g4k24u-go 
  name: dr6g4k24u-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dr6g4k24u-go 
